# -*- coding: utf-8 -*-
"""Finpro_Program Pembelian Tiket Pesawat Bandara Trunojoyo_A

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n1KjWebGAITmrbY6_81dsV5BTa7FRbuO

## Nama  : Nurmalita Fitri Ramadani
## NPM   : 21083010067
## Kelas : Sistem Operasi A
"""

#import library
tiket = []
all = []

#list harga
BT1=290000
BT2=301100
BT3=280000
BT4=305500
BT5=303600
BT6=303600
BT7=302500
BT8=300500

while True:
  print ("\n")
  print ("+==========================================================+")
  print ("|  SELAMAT DATANG DI AGEN TIKET PESAWAT BANDARA TRUNOJOYO  |")
  print ("|                                                          |")
  print ("|        Silahkan Melakukan Proses Pemesanan Tiket         |")
  print ("+----------------------------------------------------------+")
  print ("| A. Pesan Tiket                                           |")
  print ("| B. Keluar                                                |")
  print ("+==========================================================+")
  proses = str(input("Masukkan Abjad Pilihan: "))

  if proses == "A":
    print ("\n")
    print ("+=============================================================+")
    print ("||                    Detail Informasi Tiket                 ||")
    print ("---------------------------------------------------------------")
    print ("||        RUTE         |      JAM      |    HARGA    |  KODE ||")
    print ("---------------------------------------------------------------")
    print ("||Banyuwangi - Sumenep  | 13:10 - 13:50 | Rp. 290.000 |  BT1 ||")
    print ("||Bawean - Sumenep      | 08:10 - 09:05 | Rp. 301.100 |  BT2 ||")
    print ("||Pagerungan - Sumenep  | 10:50 - 11:50 | RP. 280.000 |  BT3 ||")
    print ("||Surabaya - Sumenep    | 15:00 - 15:30 | Rp. 305.500 |  BT4 ||")
    print ("||Sumenep - Banyuwangi  | 12:20 - 13:00 | RP. 303.610 |  BT5 ||")
    print ("||Sumenep - Bawean      | 08:00 - 08:55 | Rp. 303.610 |  BT6 ||")
    print ("||Sumenep - Pagerungan  | 12:40 - 13:40 | Rp. 302.500 |  BT7 ||")
    print ("||Sumenep - Surabaya    | 09:00 - 09:30 | Rp. 300.500 |  BT8 ||")
    print ("+=============================================================+")
    kode = str(input("Masukkan KODE dari Rute yang Akan Dipesan: "))
    if kode == "BT1":
      harga1 = BT1
      a = int(input("Jumlah Penumpang: "))
      jumlah1 = harga1 * a
      tiket.append(["Banyuwangi - Sumenep", a, jumlah1])
      all.append(jumlah1)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", a                                 )
      print ( "Total Pembayaran : Rp.", jumlah1                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break
    
    else:
          next
    if kode == "BT2":
      harga2 = BT2
      b = int(input("Jumlah Penumpang: "))
      jumlah2 = harga2 * b
      tiket.append(["Bawean - Sumenep", b, jumlah2])
      all.append(jumlah2)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", b                                 )
      print ( "Total Pembayaran : Rp.", jumlah2                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break

    else:
          next
    if kode == "BT3":
      harga3 = BT3
      c = int(input("Jumlah Penumpang: "))
      jumlah3 = harga3 * c
      tiket.append(["Pagerungan - Sumenep", c, jumlah3])
      all.append(jumlah3)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", c                                 )
      print ( "Total Pembayaran : Rp.", jumlah3                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break

    else:
          next
    if kode == "BT4":
      harga4 = BT4
      d = int(input("Jumlah Penumpang: "))
      jumlah4 = harga4 * d
      tiket.append(["Surabaya - Sumenep", d, jumlah4])
      all.append(jumlah4)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", d                                 )
      print ( "Total Pembayaran : Rp.", jumlah4                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break
    
    else:
          next
    if kode == "BT5":
      harga5 = BT5
      e = int(input("Jumlah Penumpang: "))
      jumlah5 = harga5 * e
      tiket.append(["Sumenep - Banyuwangi", e, jumlah5])
      all.append(jumlah5)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", e                                 )
      print ( "Total Pembayaran : Rp.", jumlah5                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break

    else:
          next
    if kode == "BT6":
      harga6 = BT6
      f = int(input("Jumlah Penumpang: "))
      jumlah6 = harga6 * f
      tiket.append(["Sumenep - Bawean", f, jumlah6])
      all.append(jumlah6)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", f                                 )
      print ( "Total Pembayaran : Rp.", jumlah6                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break

    else:
          next
    if kode == "BT7":
      harga7 = BT7
      g = int(input("Jumlah Penumpang: "))
      jumlah7 = harga7 * g
      tiket.append(["Sumenep - Pagerungan", g, jumlah7])
      all.append(jumlah7)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", g                                 )
      print ( "Total Pembayaran : Rp.", jumlah7                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break

    else:
          next
    if kode == "BT8":
      harga8 = BT8
      h = int(input("Jumlah Penumpang: "))
      jumlah8 = harga8 * h
      tiket.append(["Sumenep - Surabaya", h, jumlah8])
      all.append(jumlah8)
      print ("\n")
      print ("===========================================================")
      print ("||                  INFORMASI PEMBAYARAN                 ||")
      print ("===========================================================")
      print ( "Kode Penerbangan :", kode                                )
      print ( "Jumlah penumpang :", h                                 )
      print ( "Total Pembayaran : Rp.", jumlah8                        )
      print ("       -----------------------------------------       ")
      print ("           -------------------------------            ")
      print ("        Silahkan Melakukan Pembayaran di Kasir         ")
      print ("    Selamat Jalan dan Semoga Selamat Sampai Tujuan     ")
      print ("===========================================================")
      break

    else:
      print ("\n")
      print ("-----------------------------------------------------------")
      print ("|                        Notification                     |")
      print ("-----------------------------------------------------------")
      print ("|Input Yang Anda Masukkan Salah!                          |")
      print ("-----------------------------------------------------------")

  elif proses == "B":
    print ("\n")
    print ("-----------------------------------------------------------")
    print (" Pemesanan Berhenti...                                     ")
    print ("-----------------------------------------------------------")
    break

