print ("---------------------------------")
print ("TUGAS 1 SISOP KELAS A")
print ("---------------------------------")
print ("Nama : Nurmalita Fitri Ramadani")
print ("NPM : 21083010067")
print ("---------------------------------")
print ("notes :")
print ("---------------------------------")
print ("Halo dunia!")
print ("this is my first Bash Script in Linux")
